name: Run Tests

on:
  push:
    paths:
      - 'hopverkefni-1/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'hopverkefni-1/**'
    branches: [ main ]
  workflow_dispatch:  # This allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./hopverkefni-1

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './hopverkefni-1/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create .env file
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/testdb" > .env
          echo "JWT_ACCESS_SECRET=github_actions_test_secret" >> .env
          
      - name: Generate Prisma client
        run: npx prisma generate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
          JWT_ACCESS_SECRET: github_actions_test_secret
        
      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
          JWT_ACCESS_SECRET: github_actions_test_secret
        
      - name: Seed the database
        run: npm run seed
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
          JWT_ACCESS_SECRET: github_actions_test_secret
        
      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
          JWT_ACCESS_SECRET: github_actions_test_secret